# Generated by Django 3.1.5 on 2021-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
