# Generated by Django 3.1.5 on 2021-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
