# Generated by Django 3.1.5 on 2021-02-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210219_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish',
        ),
    ]
