# Generated by Django 3.1.5 on 2021-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
