# Generated by Django 3.1.5 on 2021-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210219_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(blank=True, default=None, max_length=122),
            preserve_default=False,
        ),
    ]
