# Generated by Django 3.1.5 on 2021-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210219_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
