# Generated by Django 3.1.5 on 2021-06-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_commentmode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentMode',
            new_name='CommentModel',
        ),
    ]
