# Generated by Django 3.1.5 on 2021-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210704_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
